# Welcome to Jekyll!
#
title: Fiona Maclay's Portfolio
  # email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The professional portfolio of Fiona Maclay.
baseurl: "" # the subpath of your site, e.g. /blog
url: "fionamaclay.github.io" # the base hostname & protocol for your site, e.g. http://example.com
  # twitter_username: jekyllrb
github_username:  fionamaclay

# Build settings
# theme: jekyll-theme-cayman
theme: minima
# plugins:
  # - jekyll-theme-cayman
  # - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
